In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from config_fields import fields
import pandas as pd
import numpy as np

In [3]:
NUM_MED_SET = 100
NUM_ID_SET  = 1000

In [4]:
def determine_functions(fields: list):
    names: list[str] = []
    function: list = []

    for field in fields:
        if field.choice not in field.options:
            raise ValueError(
                f'Choice not in list of options for {field.name}. Review configuration file.'
            )
        
        names.append(field.name)

        index = field.options.index(field.choice)
        function.append(field.functions[index])

    return dict(zip(names, function))

In [5]:
functions = determine_functions(fields)
functions['age'](10)

array([19,  8, 22,  4,  6, 16, 23,  1,  5, 10])

In [6]:
def make_medical_data(fields:list, n:int):
    functions = determine_functions(fields)
    df = pd.DataFrame()

    for field in fields:
        df[field.name] = functions[field.name](n)

    return df

In [ ]:
def make_data(fields: list, n_med: int, n_id: int, n_overlap: int):
    functions = determine_functions(fields)
    med_data = pd.DataFrame()
    id_data = pd.DataFrame()

    for field in fields:
        med_data[field.name] = functions[field.name](n_med)
        id_data[field.name] = functions[field.name](n_id - n_overlap)

    overlap_data = med_data.sample(n = n_overlap)
    id_data = pd.concat([id_data, overlap_data]).sample(frac=1).reset_index(drop=True)

    return id_data, med_data

In [58]:
id, med = make_data(fields, 5, 10, 2)

In [59]:
id

  address  age     sex conditions
0     N4S   17  female        N/A
1     V3M   24    male        N/A
2     M4R   12  female        N/A
3     S0N    2    male        N/A
4     E7K   10    male        N/A
5     J3L   10  female        N/A
6     L6K    0  female        N/A
7     K0L   15  female        N/A
8     L6S   15    male        N/A
9     R3P    9  female        N/A

In [60]:
med

  address  age     sex conditions
0     J0E   15  female        N/A
1     L9B    8    male        N/A
2     K4B   23    male        N/A
3     S0N    2    male        N/A
4     L6K    0  female        N/A