In [4]:
import numpy as np
import pandas as pd

In [1]:
def cross_entropy(data_p, data_q):
     #data_q is the ID dataset
     #data_p is the medical dataset
     #Drop all non-shared columns
     for col_name in data_p.columns:
         if col_name in data_q.columns:
             data_p = data_p
         else:
             data_p = data_p.drop(columns = col_name)
     for col_name in data_q.columns:
         if col_name in data_p.columns:
             data_q = data_q
         else: 
             data_q = data_q.drop(columns = col_name)
     #Convert to arrays
     arr1 = data_p.to_numpy()
     arr2 = data_q.to_numpy()
     arr1 = arr1.astype('U21')
     arr2 = arr2.astype('U21')
     counts1, counts2 = data_counts(arr1,arr2) 
     prob1 = [x / len(arr1) for x in counts1]
     prob2 = [x / len(arr2) for x in counts2]
     entropy =0
     for i in range(len(prob1)):
         if prob2[i] == 0:
             # Ignore entries that clearly aren't in both datasets
             entropy = entropy
         elif prob1[i] == 0:
              entropy= entropy
         else:
             entropy = entropy - prob1[i]*np.log2(prob2[i])
     return(entropy)

In [2]:
def data_counts(data_array1, data_array2):
    entries1, counts1 = np.unique(data_array1, axis = 0, return_counts = True)
    ent1 = entries1.tolist()
    co1 = counts1.tolist()
    entries2, counts2 = np.unique(data_array2, axis = 0, return_counts = True)
    ent2 = entries2.tolist()
    co2 = counts2.tolist()
    co2_sorted = [None]*len(co1)
    for i in range(len(ent1)):
        if (ent1[i] in ent2) == True:
            j = ent2.index(ent1[i])
            co2_sorted[i] = co2[j]
        else:
            co2_sorted[i] = 0    
    return(co1, co2_sorted)

In [5]:
df1 = pd.read_csv("data1.csv")
df2 = pd.read_csv("data2.csv")

In [6]:
cross_entropy(df1,df2)

(np.float64(1.5818636156147465), np.float64(1.923191719762238), 5)

In [6]:
df1.head(5)

    Last Name Province  Gender Smokes
0       Jones       BC  female     no
1      Anklam       ON  female     no
2      Elwell       QB   other     no
3    Sprinkle       NB    male     no
4  Williamson       QB  female     no

In [7]:
df2.head(5)

   Gender Smokes Has cancer  Depression Score
0  female    yes        yes                 0
1    male     no         no                40
2    male     no        yes                30
3    male     no         no                50
4  female     no        yes                60

In [10]:
df1 = df1.drop(columns = ["Smokes"])

In [11]:
df2 = df2.drop(columns = ["Smokes"])

In [12]:
cross_entropy(df1,df2)

(np.float64(1.3339838563280082), np.float64(1.4628636716739858))

In [13]:
cross_entropy(df1.head(10),df2.head(10))

(np.float64(1.4269790471552188), np.float64(1.5609640474436812))

In [14]:
df1.head(10)

    Last Name Province  Gender
0       Jones       BC  female
1      Anklam       ON  female
2      Elwell       QB   other
3    Sprinkle       NB    male
4  Williamson       QB  female
5     Sandage       ON    male
6   Mccormick       QB  female
7     Kindred       BC    male
8       Smith       AB  female
9       Tubbs       BC    male