In [1]:
import numpy as np
import pandas as pd
import re

In [24]:
def parse_age_to_interval(age_str):
    # "0 to 4 years" → Interval(0, 4, closed='left')
    m = re.match(r'(\d+) to (\d+)', age_str)
    if m:
        return pd.Interval(int(m.group(1)), int(m.group(2)) + 1, closed='left')
    
    # "100+" → Interval(100, inf, closed='left')
    m = re.match(r'(\d+) years and ', age_str)
    if m:
        return pd.Interval(int(m.group(1)), np.inf, closed='left')
    
    return pd.NA

In [46]:
age_sex = pd.read_csv(
    '../data/bayesian_network/province-age-sex.csv',
    skiprows=[0,1,2,3,4,5,6,7,10,11],
    header=[0,1],
    index_col=0,
)[0:21]
age_sex.columns.names = ['geography', 'gender']
age_sex.index.name = 'age_group'

geo = (
    age_sex.columns.get_level_values('geography')
    .to_series()
    .replace(r'^Unnamed.*', pd.NA, regex=True)
    .ffill()
)
age_sex.columns = pd.MultiIndex.from_arrays(
    [geo.values, age_sex.columns.get_level_values('gender')],
    names=['geography', 'gender']
)

age_sex = age_sex.apply(lambda col: pd.to_numeric(col.astype(str).str.replace(',', ''), errors='coerce'))
age_sex.index = age_sex.index.map(parse_age_to_interval)

In [47]:
result = (
    age_sex
    .stack(['geography', 'gender'])
    .unstack('geography')
    .swaplevel('age_group', 'gender')
    .sort_index()
)
result['Canada (excluding territories)'] = result.sum(axis=1)
result = result.rename(
    columns = {
        'Canada (except provinces)': 'Canada (excluding territories)'
    },
    index = {
        'Men+': 'Male',
        'Women+': 'Female'
    }
)

In [48]:
result

geography             Alberta  British Columbia  Manitoba  New Brunswick  \
gender age_group
Male   [0.0, 5.0)      131507            114559     42204          17188
       [5.0, 10.0)     146831            130524     46198          20019
       [10.0, 15.0)    147785            136018     45458          21147
       [15.0, 20.0)    137819            143876     44308          21076
       [20.0, 25.0)    142181            172054     56853          23635
       [25.0, 30.0)    156448            205321     54726          24116
       [30.0, 35.0)    175956            210865     51332          23779
       [35.0, 40.0)    183812            197455     49338          24432
       [40.0, 45.0)    169950            176719     45948          24694
       [45.0, 50.0)    149538            159522     42121          25179
       [50.0, 55.0)    139375            165387     40380          26545
       [55.0, 60.0)    137765            173844     42395          30300
       [60.0, 65.0)    137959            176121     43588          31198
       [65.0, 70.0)    115285            158345     37206          28824
       [70.0, 75.0)     82947            132486     28736          24013
       [75.0, 80.0)     55748             94164     20286          16670
       [80.0, 85.0)     33210             57626     12130           9774
       [85.0, 90.0)     18600             32340      6451           4803
       [90.0, 95.0)      7598             13816      2689           1809
       [95.0, 100.0)     1572              2990       688            354
       [100.0, inf)       151               312        74             33
Female [0.0, 5.0)      125380            109755     40567          16267
       [5.0, 10.0)     139035            123942     43211          19412
       [10.0, 15.0)    138576            127288     42745          20445
       [15.0, 20.0)    129966            136564     41119          19981
       [20.0, 25.0)    133646            167361     48779          21971
       [25.0, 30.0)    149543            194649     48077          22426
       [30.0, 35.0)    173723            203362     48182          23626
       [35.0, 40.0)    179643            192885     47045          24940
       [40.0, 45.0)    164595            177099     44613          24962
       [45.0, 50.0)    144058            166307     41102          26199
       [50.0, 55.0)    135343            175691     40225          26776
       [55.0, 60.0)    136210            180918     42857          30974
       [60.0, 65.0)    137882            186585     43994          32475
       [65.0, 70.0)    117424            171421     38557          30510
       [70.0, 75.0)     87964            143067     31755          25649
       [75.0, 80.0)     61636            103752     23008          18409
       [80.0, 85.0)     40305             68388     15603          11899
       [85.0, 90.0)     26323             43004     10318           7272
       [90.0, 95.0)     14223             23484      6133           3649
       [95.0, 100.0)     4417              7624      2083           1220
       [100.0, inf)       802              1355       416            219

geography             Newfoundland and Labrador  Nova Scotia  Ontario  \
gender age_group
Male   [0.0, 5.0)                         10041        21563   365599
       [5.0, 10.0)                        11924        24838   402965
       [10.0, 15.0)                       13197        26219   419881
       [15.0, 20.0)                       14026        26067   443227
       [20.0, 25.0)                       15191        33807   539339
       [25.0, 30.0)                       14370        35632   601163
       [30.0, 35.0)                       14988        33721   570277
       [35.0, 40.0)                       15323        31819   520197
       [40.0, 45.0)                       15714        29804   471705
       [45.0, 50.0)                       16864        29837   451093
       [50.0, 55.0)                       19037        31562   470484
       [55.0, 60.0)                       21041        37185   512759
       [60.0, 65.0)                       21495        38994   494748
       [65.0, 70.0)                       20219        34610   408097
       [70.0, 75.0)                       17136        28476   330157
       [75.0, 80.0)                       11860        20519   241334
       [80.0, 85.0)                        6268        11713   149366
       [85.0, 90.0)                        2945         6057    85288
       [90.0, 95.0)                         942         2163    35409
       [95.0, 100.0)                        145          419     8035
       [100.0, inf)                          19           55      770
Female [0.0, 5.0)                          9544        20595   349742
       [5.0, 10.0)                        11356        23943   382394
       [10.0, 15.0)                       12533        24609   394876
       [15.0, 20.0)                       12860        24128   413027
       [20.0, 25.0)                       13786        30390   489099
       [25.0, 30.0)                       13246        32910   544841
       [30.0, 35.0)                       14725        33451   544349
       [35.0, 40.0)                       15483        31898   515155
       [40.0, 45.0)                       16353        31411   482740
       [45.0, 50.0)                       17523        31025   474920
       [50.0, 55.0)                       19810        33554   496566
       [55.0, 60.0)                       21764        38801   528132
       [60.0, 65.0)                       22088        40963   513123
       [65.0, 70.0)                       21244        36886   445799
       [70.0, 75.0)                       18422        31214   370880
       [75.0, 80.0)                       13144        23253   277745
       [80.0, 85.0)                        7802        14821   190601
       [85.0, 90.0)                        4292         8928   124747
       [90.0, 95.0)                        1886         4506    68926
       [95.0, 100.0)                        547         1395    22748
       [100.0, inf)                         104          293     3533

geography             Prince Edward Island  Quebec  Saskatchewan  \
gender age_group
Male   [0.0, 5.0)                     3615  218495         36338
       [5.0, 10.0)                    4369  240168         39998
       [10.0, 15.0)                   4583  244876         40476
       [15.0, 20.0)                   4678  225890         37127
       [20.0, 25.0)                   6550  247872         37913
       [25.0, 30.0)                   5845  286241         39440
       [30.0, 35.0)                   5001  296451         42060
       [35.0, 40.0)                   4849  286815         42895
       [40.0, 45.0)                   4807  303835         40357
       [45.0, 50.0)                   4893  275462         35067
       [50.0, 55.0)                   5108  264176         32695
       [55.0, 60.0)                   5712  302484         35712
       [60.0, 65.0)                   5813  313768         37906
       [65.0, 70.0)                   5174  273391         33759
       [70.0, 75.0)                   4450  220283         24814
       [75.0, 80.0)                   3155  163693         16892
       [80.0, 85.0)                   1684   95671         10591
       [85.0, 90.0)                    899   49702          5910
       [90.0, 95.0)                    347   20534          2842
       [95.0, 100.0)                    74    4114           700
       [100.0, inf)                      6     380            67
Female [0.0, 5.0)                     3559  206415         34590
       [5.0, 10.0)                    4058  227744         37943
       [10.0, 15.0)                   4498  234337         37795
       [15.0, 20.0)                   4680  217369         34503
       [20.0, 25.0)                   6282  235100         34737
       [25.0, 30.0)                   5324  266901         36235
       [30.0, 35.0)                   5204  282816         40379
       [35.0, 40.0)                   5286  278628         42056
       [40.0, 45.0)                   5209  292551         38311
       [45.0, 50.0)                   5141  265732         34038
       [50.0, 55.0)                   5413  256512         32109
       [55.0, 60.0)                   6003  296299         35630
       [60.0, 65.0)                   6197  315387         37839
       [65.0, 70.0)                   5749  282630         34018
       [70.0, 75.0)                   4864  233935         25648
       [75.0, 80.0)                   3514  183037         18654
       [80.0, 85.0)                   2257  121673         13301
       [85.0, 90.0)                   1404   78535          9496
       [90.0, 95.0)                    673   44525          5605
       [95.0, 100.0)                   225   13425          1951
       [100.0, inf)                     48    2111           399

geography             Canada (excluding territories)
gender age_group
Male   [0.0, 5.0)                             961109
       [5.0, 10.0)                           1067834
       [10.0, 15.0)                          1099640
       [15.0, 20.0)                          1098094
       [20.0, 25.0)                          1275395
       [25.0, 30.0)                          1423302
       [30.0, 35.0)                          1424430
       [35.0, 40.0)                          1356935
       [40.0, 45.0)                          1283533
       [45.0, 50.0)                          1189576
       [50.0, 55.0)                          1194749
       [55.0, 60.0)                          1299197
       [60.0, 65.0)                          1301590
       [65.0, 70.0)                          1114910
       [70.0, 75.0)                           893498
       [75.0, 80.0)                           644321
       [80.0, 85.0)                           388033
       [85.0, 90.0)                           212995
       [90.0, 95.0)                            88149
       [95.0, 100.0)                           19091
       [100.0, inf)                             1867
Female [0.0, 5.0)                             916414
       [5.0, 10.0)                           1013038
       [10.0, 15.0)                          1037702
       [15.0, 20.0)                          1034197
       [20.0, 25.0)                          1181151
       [25.0, 30.0)                          1314152
       [30.0, 35.0)                          1369817
       [35.0, 40.0)                          1333019
       [40.0, 45.0)                          1277844
       [45.0, 50.0)                          1206045
       [50.0, 55.0)                          1221999
       [55.0, 60.0)                          1317588
       [60.0, 65.0)                          1336533
       [65.0, 70.0)                          1184238
       [70.0, 75.0)                           973398
       [75.0, 80.0)                           726152
       [80.0, 85.0)                           486650
       [85.0, 90.0)                           314319
       [90.0, 95.0)                           173610
       [95.0, 100.0)                           55635
       [100.0, inf)                             9280

In [49]:
result.to_csv('../data/bayesian_network/age-fixed.csv')

------------------------------------

In [50]:
data2 = pd.read_csv(
    '../data/bayesian_network/age-sex-health.csv',
    skiprows=[0,1,2,3,4,5,6,7,8,11,12],
    header=[0,1],
    index_col=0
)[:4]
data2.columns.names = ['age_group', 'sex']
data2.index.name = 'condition'

filled_columns = (
    data2.columns.get_level_values('age_group')
    .to_series()
    .replace(r'^Unnamed.*', pd.NA, regex=True)
    .ffill()
)

data2.columns = pd.MultiIndex.from_arrays(
    [filled_columns.values, data2.columns.get_level_values('sex')],
    names=['age_group', 'sex']
)

data2 = data2.apply(lambda col: col.astype(str).str.replace('E', ''))
data2 = data2.apply(lambda col: pd.to_numeric(col.astype(str).str.replace(',', ''), errors='coerce'))
data2 = data2.drop(columns=['Total, 18 years and over'])

C:\Users\ltyih\AppData\Local\Temp\ipykernel_24812\1872592946.py:24: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  data2 = data2.drop(columns=['Total, 18 years and over'])

In [51]:
data2.columns = pd.MultiIndex.from_arrays(
    [data2.columns.get_level_values('age_group').map(parse_age_to_interval),
     data2.columns.get_level_values('sex')],
    names=['age_group', 'sex']
)

In [52]:
data2

age_group                                          [18.0, 35.0)           \
sex                                                       Males  Females
condition
Body mass index, adjusted self-reported, adult ...       955200   974800
High blood pressure 21 22                                122900    84600
Current smoker, daily or occasional 23 24 25 26 27       562800   330200
Influenza immunization in the past 12 months 28 29       647100  1037900

age_group                                          [35.0, 50.0)           \
sex                                                       Males  Females
condition
Body mass index, adjusted self-reported, adult ...      1258100  1132100
High blood pressure 21 22                                442000   308100
Current smoker, daily or occasional 23 24 25 26 27       626900   425100
Influenza immunization in the past 12 months 28 29       812500  1181800

age_group                                          [50.0, 65.0)           \
sex                                                       Males  Females
condition
Body mass index, adjusted self-reported, adult ...      1284600  1185800
High blood pressure 21 22                               1130600   913300
Current smoker, daily or occasional 23 24 25 26 27       649900   572000
Influenza immunization in the past 12 months 28 29      1215600  1454300

age_group                                          [65.0, inf)
sex                                                      Males  Females
condition
Body mass index, adjusted self-reported, adult ...      869500  1045400
High blood pressure 21 22                              1440800  1700900
Current smoker, daily or occasional 23 24 25 26 27      325600   304300
Influenza immunization in the past 12 months 28 29     1932500  2284600

In [53]:
pivot2 = (
    data2
    .stack(['age_group', 'sex'])
    .unstack(['condition'])
    .swaplevel('age_group', 'sex')
    .sort_index()
)

pivot2 = pivot2.rename(
    columns = {
        'Body mass index, adjusted self-reported, adult (18 years and over), obese 15 16 17 18 19 20': 'Obese',
        'High blood pressure 21 22': 'High blood pressure',
        'Current smoker, daily or occasional 23 24 25 26 27': 'Current smoker',
        'Influenza immunization in the past 12 months 28 29': 'Recently vaccinated'
    },
    index = {
        'Males': 'Male',
        'Females': 'Female'
    }
)
pivot2

condition              Obese  High blood pressure  Current smoker  \
sex    age_group
Female [18.0, 35.0)   974800                84600          330200
       [35.0, 50.0)  1132100               308100          425100
       [50.0, 65.0)  1185800               913300          572000
       [65.0, inf)   1045400              1700900          304300
Male   [18.0, 35.0)   955200               122900          562800
       [35.0, 50.0)  1258100               442000          626900
       [50.0, 65.0)  1284600              1130600          649900
       [65.0, inf)    869500              1440800          325600

condition            Recently vaccinated
sex    age_group
Female [18.0, 35.0)              1037900
       [35.0, 50.0)              1181800
       [50.0, 65.0)              1454300
       [65.0, inf)               2284600
Male   [18.0, 35.0)               647100
       [35.0, 50.0)               812500
       [50.0, 65.0)              1215600
       [65.0, inf)               1932500

In [54]:
pivot2.to_csv('../data/bayesian_network/health-fixed.csv', index=True)